INSERT INTO formations VALUES
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique),
(Licence Informatique, Formation en informatique, Licence, Informatique, Aucun prérequis),
(Master Informatique, Formation en informatique avancée, Master, Informatique, Licence en Informatique);